### ISSUE TITLE
crashes game

### ISSUE THREAD

**Issue by heapframe** [user-grinch/PyLoaderSA#11]
log : `------------------------------
Starting PyLoader v0.09
Author: Grinch_
Thanks: CLEO4 & PluginSDK devs
More info: https:///github.com/user-grinch/PyLoaderSA/
No updates found
------------------------------
Injecting SoundSystem...
Found sound device 0 No sound
Found sound device 1 (default)PulseAudio
On system found 2 devices, 2 enabled devices, assuming device to use: 1 PulseAudio
Could not initialize BASS sound system
`

modloader backtrace:

`Game version: GTA SA 1.0 US
Unhandled exception at 0x06B78E86 in pyloader.asi (+0x28e86): 0xC0000005: Access violation reading location 0x00000000.
    Register dump:
        EAX: 0xFFFFFFFF  EBX: 0x00000000  ECX: 0x65D637A8  EDX: 0x00000000  
        EDI: 0x00000000  ESI: 0x06E57F20  EBP: 0x50ADFF30  EIP: 0x06B78E86  
        ESP: 0x50ADFEDC  EFL: 0x00010246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000006B   FS: 0x00000063   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x50ADFEDC:  357BC898 00000000 00000000 00000000 00000000 00000000
        0x50ADFEF4:  00000000 06C05E80 00000000 00000000 00000000 7362696C
        0x50ADFF0C:  00006474 00000000 00000000 00000006 0000000F 357BC898
        0x50ADFF24:  50ADFF8C 06BD9B65 FFFFFFFF 50ADFF48 7B62DE80 00000000
        0x50ADFF3C:  7BC57A37 7BC57A37 00000000 50ADFF5C 7BC57A37 00000000
        0x50ADFF54:  00000000 00000000 50ADFFEC 7BC580F0 7B62DE70 06B78C20
        0x50ADFF6C:  00000000 00000000 00000000 00000000 00000000 00000000
        0x50ADFF84:  00000000 00000000 FFFFFFFF 7BC62D70 7BC236C0 00000000
        0x50ADFF9C:  50ADFFEC 00000000 00000000 00000000 50ADFF60 7BC58069
        0x50ADFFB4:  00000000 00000000 00000000 00000000 00000000 00000000
        base: 0x508E0000   top: 0x50ADFEDC   bottom: 0x50AE0000
        
    Backtrace (may be wrong):
        =>0x06B78E86 in pyloader.asi (+0x28e86) (0x50ADFF30) 
          0x7B62DE80 BaseThreadInitThunk+0x10 in kernel32.dll (+0x2de80) (0x50ADFF48) 
          0x7BC57A37 RtlUserThreadStart+0x27 in ntdll.dll (+0x57a37) (0x50ADFF5C) 
          0x7BC580F0 RtlCreateUserThread+0x0 in ntdll.dll (+0x580f0) (0x50ADFFEC)
`

**Comment by user-grinch** [comment]
Need more info. What mods have you got installed?

**Comment by heapframe** [comment]
Definitive_Radar_Map_Collection      IMFX_by_DK22Pac
 Enterable_Hidden_Interiors	      Loadscreens_4K_Definitive
'fix face animations'		      modloader.ini
 FramerateVigilante		      modloader.log
'GPS Mod'			      Open_Limit_Adjuster
 GraphicsTweaker		     'run indoors'
 GTA_IV_HUD_by__AG		      SA_VC_III_-_Windowed_Mode
 GTA_V_Animation_Loading_Bar_for_SA  'silent patch'
'hd cj'				      widescreenfix

**Comment by heapframe** [comment]
im not using cleo

**Comment by user-grinch** [comment]
Can you contact me on the discord server? It'd be easier there.
