### ISSUE TITLE
How to import site-packages?

### ISSUE THREAD

**Issue by mgmoldova** [user-grinch/PyLoaderSA#3]
I want to use pandas library in my script. 
How to install it in PyLoader/python38?

**Comment by user-grinch** [comment]
Aight so, you'll need to rebuild the plugin & extension with the lastest commit. After that go into the PyLoader\lib folder in cmd and run `pip install <package_name> -t .` (assuming you have pip installed). You should be able to use your modules as usual after that.

```
import numpy as np
while True:
    common.wait(0)
    
    if common.key_pressed(0xA0):
            a = np.arange(10,25,5)
            print(a)
```

**Comment by mgmoldova** [comment]
Thanks!
