### ISSUE TITLE
Adding automated CI Builds

### ISSUE THREAD

**Issue by justalemon** [user-grinch/PyLoaderSA#4]
Would it be possible to get CI builds? (AppVeyor, Travis CI, GitHub Actions, etc) So there are test builds available after every commit that we can test.

**Comment by user-grinch** [comment]
I don't have much experience with them atm but I'll take a look.

**Comment by justalemon** [comment]
If you want, I can go ahead and try to make a Pull Request.

**Comment by user-grinch** [comment]
Feel free
